### ISSUE TITLE
Version not written in pkg-config

### ISSUE THREAD

**Issue by fbleibel** [jrl-umi3218/jrl-mathtools#4]
With the update of the cmake/ build tools, the .pc file is badly generated:
(contents of jrl-mathtools.pc)
(...)
Name: jrl-mathtools
Description: JRL mathematical tools
URL: http://github.com/jrl-umi3218/jrl-mathtools
Version: UNKNOWN
(...)

The UNKNOWN prevents pkg-config from finding this dependency (jrl-mathtools >= 1.0.0 fails for example).

**Comment by thomas-moulard** [comment]
Please run `git describe --abbrev=4 --match='v*' HEAD` locally.

Also, be careful to the error message at the beginning of the cmake configuration process (when you type `cmake <BUILDDIR>`), it should explain why the version cannot be detected automatically.

Documentation regarding version generation is available in `cmake/version.cmake` (cf https://github.com/jrl-umi3218/jrl-cmakemodules/raw/master/version.cmake)

**Comment by fbleibel** [comment]
Solved by updating git version. I don't think there's a need to push this issue further since it works with git --version >= 1.7.3
